### ISSUE TITLE
Is there a way to save in JSON or CSV?

### ISSUE THREAD

**Issue by alberttwong** [devinrsmith/deephaven-parquet-viewer#20]
I was wondering if the viewer can save in JSON or CSV.

**Comment by devinrsmith** [comment]
Yes, there is an export / download to CSV option, but it looks like there's an upstream bug that is making it not available by default for iframes: https://github.com/deephaven/web-client-ui/issues/1337

To work around this, you can view the table in the ide, http://localhost:10000/ide/, and then there should be a "Download CSV" option in the menu options for the `parquet_table`.

I may be able to get out a fix for this sooner rather than later, I will let you know.

**Comment by devinrsmith** [comment]
Actually, another workaround is to add the `canDownloadCsv` query param:

http://localhost:10000/iframe/table/?name=parquet_table&canDownloadCsv

although, I will be advocating that upstream remove this ability in the future (and download csv should be enabled by default).
