### ISSUE TITLE
token

### ISSUE THREAD

**Issue by FATMACEYDAGOKCE** [devinrsmith/deephaven-parquet-viewer#27]
How to decide token at first?

**Comment by devinrsmith** [comment]
Thanks, I forgot to update the authentication mechanism when I updated the underlying deephaven dependency. This should be fixed by the latest release / commit: https://github.com/devinrsmith/deephaven-parquet-viewer/commit/5b8325cc5f02ec9acbdb7d232eda926c87c3f511. Can you pull (or build) and try again @astro1307?

**Comment by astro1307** [comment]
it still asks me token and there is only one branch named master no release branch

**Comment by devinrsmith** [comment]
Are you running the `deephaven-parquet-viewer.sh` script, or are you trying to do something else? If so, can you try:

```
docker pull ghcr.io/devinrsmith/deephaven-parquet-viewer:latest
```

And then try again?

**Comment by devinrsmith** [comment]
I'm relatively confident this is no longer an issue.
